export ChangePasswordPage from './ChangePasswordPage'
export IndexPage from './IndexPage'
export LoginPage from './LoginPage'
export MasterPage from './MasterPage'
export ProfilePage from './ProfilePage'
export RegisterPage from './RegisterPage'
export ResetPasswordPage from './ResetPasswordPage'
export SendFeedbackPage from './SendFeedbackPage'
export VerifyEmailPage from './VerifyEmailPage'
export ViewFeedbackPage from './ViewFeedbackPage'

